[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[general]
live_config_reload = true
working_directory = "code"

[terminal]

[colors.bright]
black = "0x6e7681"
blue = "0x79c0ff"
cyan = "0x39c5cf"
green = "0x56d364"
magenta = "0xbc8cff"
red = "0xffa198"
white = "0xb1bac4"
yellow = "0xe3b341"

[colors.cursor]
cursor = "0xe6edf3"
text = "0x30363d"

[colors.normal]
black = "0x484f58"
blue = "0x58a6ff"
cyan = "0x39c5cf"
green = "0x3fb950"
magenta = "0xbc8cff"
red = "0xff7b72"
white = "0xb1bac4"
yellow = "0xd29922"

[colors.primary]
background = "0x30363d"
foreground = "0xe6edf3"

[font]
size = 14

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.offset]
x = 2
y = 1

[scrolling]
history = 100000
multiplier = 2

[terminal.shell]
args = ["-l", "-c", "tmux -2 attach || tmux"]
program = "/bin/zsh"

[window]
decorations = "none"
opacity = 1
startup_mode = "Maximized"

[window.padding]
x = 4
y = 4

[keyboard]
